Get the owner_org of a Gemini document from the harvest source
Creation of new Gemini documents is failing with a validation error
about a missing owner_org:

Here's the stack trace from the ckan log:

```
2019-03-10 16:19:10,207 DEBUG [ckanext.spatial.validation.validation] Starting validation against profile(s) iso19139eden,constraints-1.4,gemini2-1.3
2019-03-10 16:19:10,232 DEBUG [ckanext.spatial.validation.validation] Validated against "ISO19139 XSD Schema (EDEN 2009-03-16)"
2019-03-10 16:19:10,267 DEBUG [ckanext.spatial.validation.validation] Validated against "ISO19139 Table A.1 Constraints Schematron (Medin/Parslow 1.4)"
2019-03-10 16:19:10,360 DEBUG [ckanext.spatial.validation.validation] Validated against "GEMINI 2.1 Schematron 1.3"
2019-03-10 16:19:10,360 INFO  [ckanext.spatial.validation.validation] Validation passed
2019-03-10 16:19:11,627 INFO  [ckanext.spatial.harvesters.gemini.import] No package with GEMINI guid 7a2c0411-dd5a-4c0e-8b43-c8c7fc49a095 found, let's create one
2019-03-10 16:19:11,738 ERROR [ckanext.spatial.harvesters.gemini.import] Exception during import: Traceback (most recent call last):
  File "/data/vhost/ckan/shared/venv/lib/python2.7/site-packages/ckanext/spatial/harvesters/gemini.py", line 71, in import_stage
    self.import_gemini_object(harvest_object.content)
  File "/data/vhost/ckan/shared/venv/lib/python2.7/site-packages/ckanext/spatial/harvesters/gemini.py", line 103, in import_gemini_object
    package_dict = self.write_package_from_gemini_string(unicode_gemini_string)
  File "/data/vhost/ckan/shared/venv/lib/python2.7/site-packages/ckanext/spatial/harvesters/gemini.py", line 323, in write_package_from_gemini_string
    package = self._create_package_from_data(package_dict)
  File "/data/vhost/ckan/shared/venv/lib/python2.7/site-packages/ckanext/spatial/harvesters/gemini.py", line 472, in _create_package_from_data
    raise Exception('Validation Error: %s' % str(e.error_summary))
Exception: Validation Error: {'Owner org': 'An organization must be
provided'}
```

Harvesting new versions of existing Gemini documents is working
fine. The owner_org validation is explicitly disabled for updates:

https://github.com/ckan/ckan/blob/71e359b604b79362313833b6d9d7f68ea78ce15e/ckan/logic/schema.py#L152-L175

The Base harvester has logic to set the owner_org, but the Gemini
harvester does not.  I suspect it should, and that it's missing is
just an oversight.